configure.ac
This allows the configure script to honour the PKG_CONFIG autoconf variable.
=> Use PKG_CONFIG variable in configure.ac

src/gs-lock-plug.c
This patch fixes a segfault which was the reason of an obvious
typo.  This segfault is particularly bad because it will create
a race condition by which the dialog will sometimes disappear
before telling the main screensaver program to unlock, thereby
cause the system to remain locked.
=> fix segfault due to wrong object being destroyed

src/gs-lock-plug.c
This breaks the display of the user name in dark themes. You can see an example here: https://github.com/linuxmint/mint-y-theme/issues/4
=> gs-lock-plug: Remove the hardcoded text colors

autogen.sh, configure.ac, src/Makefile.am
gnome-common is deprecating some vars and macros, listed here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829932
This change follows the gnome recommendations from:
https://wiki.gnome.org/Projects/GnomeCommon/Migration
=> Migrate away from gnome-common deprecated vars and macros

src/util/utils.py
On my system, pidof exits with status 1 when the process doesn't exist. This causes a subprocess.CalledProcessError exception to be raised. I'm not sure if this is the case everywhere, though, so I've kept the existing check logic rather than returning False in the except block and True outside
=> utils.py: handle error raised by non-zero return status

src/util/utils.py
Adds back the code for activating the display manager greeter through dbus. It is based on this pre-rewrite code:
https://github.com/linuxmint/cinnamon-screensaver/blob/7a50f015fb3a984859770ca0d51ed52eb4ead417/src/gs-lock-plug.c#L208
=> utils.py: add back alternate display manager support for user switching

autogen.sh, configure.ac, debian/control
Making the AX_ macros optional and finally dropping gnome-common build dependency, replacing it with autoconf-archive.
=> Cinnamon screensaver gnome common finish migration

src/cinnamon-screensaver-main.py
This fixed a warning
`sys:1: PyGIWarning: GdkX11 was imported without specifying a version first.Use gi.require_version('GdkX11', '3.0') before import to ensure that the right version gets loaded.
`
=> Declare GdkX11.

src/pamhelper/authClient.py
I am using the /usr/libexec path for fedora as we build for ARM and PPC
=> add libexec path

screensavers/xscreensaver@cinnamon.org/main
Fairly self explanatory. Gentoo installs xscreensaver hacks into /usr/lib/misc/xscreensaver/.
=> Add /usr/lib/misc/xscreensaver/ to the search directories list

autogen.sh
autoreconf takes care of running aclocal and other commands in the right order.
=> autogen.sh: don't run aclocal

doc/dbus-interface.html, libcscreensaver/cs-screen-x11.c, libcscreensaver/cs-screen.h, src/service.py
To test:
1. open a terminal window
2. run `$ xwininfo` and click the terminal title bar to get the window id
3. run `$ xdg-screensaver suspend [terminal window id]`
4. wait until the screensaver timeout elapses and the screensaver should not start
5. close the terminal window and xdg-screensaver should quit as well
6. wait until timeout elapses and the screensaver should activate
Edit: testing with a timeout below 1 minute might have weird results. xdg-screensaver seems to use a 50 second loop duration.
=> Fix xdg-screensaver suspend

src/unlock.py
related to this feature request.
#6136
I change the code for this applet just to remove the "switch user" option when the gsettings key "org.cinnamon.desktop.lockdown" "disable-user-switching" is true. I need it in Linux Mint 18.3 so I change it in this version.
Sorry for my english and maybe the code could be "cleaner" ?
=> unlock.py : gsettings key "org.cinnamon.desktop.lockdown" "disable-user-switching" consideration

src/cinnamon-screensaver-gtk3.14.css, src/cinnamon-screensaver-gtk3.18.css, src/cinnamon-screensaver-gtk3.20.css
Some themes use it and it looks bad. For example Vertex.
=> Remove border-image from the password entry

src/dbusdepot/accountsServiceClient.py
The is_loaded property somehow never gets set to True on my work
computer (both for UserManager and User instances). When this occurs,
User.get_home_dir() returns None (actually the docs are highly vague on
when get_home_dir() can be expected to return None). Since os.path.join
throws if passed a NoneType, fall back to os.path.expanduser('~') if
User.get_home_dir() is None.
=> Fall back to os.path.expanduser to find home dir.

src/clock.py
When setting a custom away message using the option "Ask for a custom message when locking the screen from the menu" or via `cinnamon-screensaver-lock-dialog`, the font from the settings is not applied. This PR fixes that.
=> Fixed wrong font being applied in custom text

src/cinnamon-screensaver-command.py, src/cinnamon-screensaver-main.py, src/util/settings.py
If a custom screensaver is configured, we abort the starting
cinnamon-screensaver daemon process to avoid two screensavers from
conflicting each other.
In cinnamon-screensaver-command, we start the custom screensaver command
if one is configured.
This patch needs accompanying patches in cinnamon-desktop and cinnamon-settings-daemon.
https://github.com/linuxmint/cinnamon-desktop/pull/134
https://github.com/linuxmint/cinnamon-settings-daemon/pull/270
=> Handle custom-screensaver-command gsettings config

meson.build
We have to use datadir to effect dbus-1.pc https://github.com/freedesktop/dbus/blob/b387bd4d2916416f1376fe9feeee61e557d571de/dbus-1.pc.in#L11
=> build: use datadir in define_variable for dbus_services_dir

src/pamhelper/authClient.py, src/pamhelper/cinnamon-screensaver-pam-helper.c, src/unlock.py
`CS_AUTH_MESSAGE_TEXT_INFO`-type output is shown on a single line under the username text, above the password input.
Trying to figure out how to take a screenshot of this...
This is especially useful when non-input PAM modules are used (for example, `fprintd` would show a message telling the user to put their finger on the scanner)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linuxmint/cinnamon-screensaver/341)
=> [Next] [WIP] Display PAM authentication client info

backup-locker/cs-backup-locker.c
When building with cmake-ninja, the warning popup.
```
../backup-locker/cs-backup-locker.c:159:1: error: no return statement in function returning non-void [-Werror=return-type]
159 | }
| ^
```
Hopefully this is the correct way to fix it.
=> Fix error: no return statement in function

src/cinnamon-screensaver.css
Ubuntu font family used. Changed to integrate better with a stock cinnamon install, should be updated to follow system font prefs in the future, but I see this as a welcome change over the monospace font, which, in my opinion shouldn't be used by default in most UI elements.
=> updated trackname and albumartist to use more suitable fonts 

libcscreensaver/meson.build
The Nix package manager used by NixOS (and available on all unix systems), uses a sandboxed environment where it is not possible to have global building dependencies. Without this change the build with fails with:
```
[13/37] Compiling C object libcscreensaver/libcscreensaver.so.0.0.0.p/meson-generated_.._cs-upower-device-proxy.c.o
FAILED: libcscreensaver/libcscreensaver.so.0.0.0.p/meson-generated_.._cs-upower-device-proxy.c.o 
gcc -Ilibcscreensaver/libcscreensaver.so.0.0.0.p -Ilibcscreensaver -I../libcscreensaver -I. -I.. -I/nix/store/0a9b4bv93s2b94q0fa2h4r0m55qy92fx-glib-2.72.3-dev/include -I/nix/store/0a9b4bv93s2b94q0fa2h4r0m55qy92fx-glib-2.72.3-dev/include/glib-2.0 -I/nix/store/i4k2ahrb0rzr7f2ni02nljcffawvpqpg-glib-2.72.3/lib/glib-2.0/include …
```
=> libcscreensaver: add missing gio-unix-2.0 dependency

src/clock.py, src/util/utils.py
Instead of unsung ints Gio flags should be used. This makes it easier to understand the meaning of the value.
=> use Gio flags instead of ints

libcscreensaver/cs-screen-x11.c
When hot-adding monitors (e.g. DisplayPort), I was seeing unobscured content behind the screensaver.  Debug mode revealed:
CsScreen received 'monitors-changed' signal from GdkScreen 25675900
Found 2 Xinerama screens on display :0
Monitor 0 is 0,0 1920 x 1080
Monitor 1 is 1920,0 1920 x 1200
Cinnamon Screensaver compiled without Solaris Xinerama support
Scale factor of 1 applied.  Monitor 0 is 0,0 1920 x 1080
Scale factor of 1 applied.  Monitor 1 is 1920,0 1920 x 1200
Screen rect (0,0-3840x1200) and 2 monitor rects (0,0-503284330x1200) DO NOT add up, skipping change notification cinnamon-screensaver
This could be caused by `total_monitors` rect being uninitialized; zero it.  Might fix #437.  Seems like this could fix #460, though the log therein does _not_ say "DO NOT add up".
Ref: #437 …
=> libscreensaver: fix detection of monitor hotplug
